### ISSUE TITLE
Where is the train code?

### ISSUE THREAD

**Issue by ghosthamlet** [nanohop/sketch-to-react-native#5]
Great project, the generated code seems like very promise. 
I checked the code in scripts/, but can't find the train code,
will you show the code or the concept behind the deep learning or how to train it?

**Comment by chrisachard** [comment]
Thanks! I know there's a ways to go, but I think it's a good first step.

The scripts/ code is almost entirely based on the google code lab project, Tensorflow for poets, so you can look here for more info about that: https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#0

It was meant to be a first version, so there is more coming (for example: to detect the difference between TextInput vs. Button vs. Switch vs. Slider) - but it's not complete yet.  I'll try to figure out how to include the training code as well.

**Comment by ghosthamlet** [comment]
Thanks.

**Comment by MikeChongCan** [comment]
Hello, @chrisachard . Is the train code available now?

**Comment by chrisachard** [comment]
@imWildCat The training code is in the repo, but the dataset isn't, so that doesn't do much good.  I'm reworking the training code as well - so once that's done I'll need to figure out a way to share the training dataset as well.  Do you have any recommendations about how to share a large training set?

**Comment by MikeChongCan** [comment]
Thank you, @chrisachard !

I am just a student having less experience about data science. I am not sure how large the dataset is. If it is a few GB, it could be shared by Google Drive. I am not sure whether it is allowed to be uploaded to Kaggle.

**Comment by MikeChongCan** [comment]
@chrisachard 

I watched WWDC 18 sessions about createML and CoreML recently and if the part about Machine Learning in this project is mainly classification, I believe this project can benefit from createML with transfer learning in the near future. I would have a look at this new feature of macOS and iOS.
