### ISSUE TITLE
Add link to readme.md defining what is "Sketch" ?

### ISSUE THREAD

**Issue by esutton** [nanohop/sketch-to-react-native#6]
I think some users, including myself, may confuse it with Google Sketch:

https://www.sketchup.com/

It sounds very cool.  Thanks for sharing your work!

**Comment by chrisachard** [comment]
Good advice, links added.  

You're welcome!  Hopefully it keeps getting better and better!

**Comment by esutton** [comment]
@chrisachard  Thanks!

I am going to add [Sketch App](https://www.sketchapp.com/)  to my budget and send it to the boss!
